[colors.bright]
black = "#75715E"
blue = "#66D9EF"
cyan = "#A1EFE4"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F9F8F5"
yellow = "#F4BF75"

[colors.normal]
black = "#272822"
blue = "#66D9EF"
cyan = "#A1EFE4"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F8F8F2"
yellow = "#F4BF75"

[colors.primary]
background = "#272822"
foreground = "#F8F8F2"

[cursor.style]
shape = "Underline"

[terminal]

[terminal.shell]
args = ["--login"]
program = "/usr/bin/fish"
