# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ksops = {
    pname = "ksops";
    version = "4.5.1";
    src = fetchurl {
      url = "https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.5.1/ksops_4.5.1_Linux_x86_64.tar.gz";
      sha256 = "sha256-lkHgOjAb8vxLmNDoN6A1HhykQ+zXposl5q8hSfuy7zA=";
    };
  };
  kubectl = {
    pname = "kubectl";
    version = "1.36.2";
    src = fetchurl {
      url = "https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl";
      sha256 = "sha256-HpBF7DK+qF2kPehfAGU1hSnqfHoVLsp4FU+6W1jCfYI=";
    };
  };
  libratbag = {
    pname = "libratbag";
    version = "b23167c644d8f78b477a5a12668b9edf22da1616";
    src = fetchFromGitHub {
      owner = "perfectra1n";
      repo = "libratbag";
      rev = "b23167c644d8f78b477a5a12668b9edf22da1616";
      fetchSubmodules = false;
      sha256 = "sha256-MDraqC1iZiKxszM1PZ0TSvJ4lGATGAi9ryExHzESqrM=";
    };
  };
  nvbroadcast = {
    pname = "nvbroadcast";
    version = "v1.1.13";
    src = fetchFromGitHub {
      owner = "Hkshoonya";
      repo = "nvidia-broadcast-linux";
      rev = "v1.1.13";
      fetchSubmodules = false;
      sha256 = "sha256-ZIyDMcbXJumMuEup5vytn0pPv5PsPeCB5FdkHvCrIrU=";
    };
  };
  talosctl = {
    pname = "talosctl";
    version = "1.13.5";
    src = fetchurl {
      url = "https://github.com/siderolabs/talos/releases/download/v1.13.5/talosctl-linux-amd64";
      sha256 = "sha256-yxIglyfAxNV9dMBZXzTUQbpJFCHh08ilFC7ZECiiAjI=";
    };
  };
}
