bind = $mainMod, V, exec, dms ipc call clipboard toggle # Clipboard: Toggle
bind = ALT, Space, exec, dms ipc call spotlight toggle # App Launcher: Toggle
bind = Super, A, exec, dms ipc call notifications toggle # Notifications: Toggle
bind = Super, S, exec, dms ipc call dash toggle media # Dashboard: Toggle
