# Body of the gen-manifests flake app (flake.nix packages.x86_64-linux.gen-manifests).
# writeShellApplication injects the shebang, `set -euo pipefail`, and a shellcheck gate —
# invoke via `nix run .#gen-manifests [-- host ...]`, not by executing this file.
#
# Regenerates manifests/<host>.txt: the committed name-version inventory of a host's closure.
# WHY: a flake.lock bump is a one-line hash change hiding hundreds of package updates (the
# real dependency set only exists after eval). Committing a sorted name-version list per host
# makes every Renovate PR / manual bump show exactly which packages changed — in the PR diff —
# and `git log -p manifests/` is a permanent, greppable per-package version history.
# Eval-only (`nix path-info --derivation` instantiates, never builds), so CI and Renovate run it.
#
# CAVEATS (docs/package-versioning.md):
#  - BUILD closure: a superset of what's installed (build-time deps included).
#  - Version-level only: a package rebuilt at the SAME version (the xdg-desktop-portal-hyprland
#    case) does NOT show here — `nix run .#whatchanged` and the switch-time nvd diff catch that.
#  - NO timestamps in output: CI regenerates and diffs this file; content must be reproducible.

if [ ! -f flake.nix ]; then
  echo "error: run from the repo root (flake.nix not found)" >&2
  exit 1
fi

hosts=()
for h in "$@"; do
  if [ -n "$h" ]; then hosts+=("$h"); fi # skip empty args (mise passes -- ${HOST:-})
done
if [ "${#hosts[@]}" -eq 0 ]; then
  while IFS= read -r h; do hosts+=("$h"); done \
    < <(find hosts -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
fi

mkdir -p manifests
for host in "${hosts[@]}"; do
  echo ">> manifest: $host" >&2
  drv=$(nix path-info --derivation ".#nixosConfigurations.$host.config.system.build.toplevel")
  {
    echo "# GENERATED by \`nix run .#gen-manifests\` — do not edit by hand."
    echo "# Name-version inventory of this host's build closure; CI regenerates + diffs it."
    # Strip /nix/store/<hash>- and .drv; drop non-package noise: fetched archives, patches,
    # -source FODs, and loose single-file build scaffolding. Cosmetic only — the manifest is
    # a diff surface, not an authoritative inventory.
    nix-store --query --requisites "$drv" \
      | sed -E 's|^/nix/store/[a-z0-9]{32}-||; s|\.drv$||' \
      | grep -Ev '\.(tar(\.[a-z0-9]+)?|tgz|txz|zip|gz|xz|bz2|zst|patch|diff|crate|whl|gem)(\?[^/]*)?$' \
      | grep -Ev '(^|-)source$' \
      | grep -Ev '\.(sh|bash|nix|json|conf|toml|yaml|yml|py|pl|rb|lock|service|desktop|rules|xml|c|h|cc|txt|pc|cfg|ini)$' \
      | sort -u
  } > "manifests/$host.txt"
done
echo ">> done: ${hosts[*]}" >&2
