#!/usr/bin/env bash
# Regenerate flake-inputs.txt — the Renovate-tracked pin list for top-level flake inputs.
#
# WHY this exists: Renovate's native `nix` manager only does version/tag lookups, so it never
# opens PRs for branch-following flake inputs (nixos-unstable, stable, …). And a single regex
# over flake.lock can't isolate the root inputs (suffixed node keys like `nixpkgs_2`, transitive
# copies, missing branch refs). So instead we mirror the repo's nvfetcher pattern: emit one
# uniform annotated line per *root* input that a single git-refs customManager tracks, and let a
# `nix flake update <input>` postUpgradeTask re-lock flake.lock (see renovate.json).
#
# Run this like you'd run `nvfetcher` — whenever you add/remove a flake input. It auto-discovers
# inputs from `nix flake metadata`, so there is no per-input config to hand-maintain.
set -euo pipefail
cd "$(dirname "$0")/.."

# Inputs we deliberately do NOT auto-update (pinned for a reason — keep them out of Renovate's
# reach). Add an input's name here to hold it at its locked rev.
SKIP=()

meta=$(nix flake metadata --json)
out="flake-inputs.txt"

{
  echo "# GENERATED by scripts/gen-flake-input-pins.sh — do not edit by hand."
  echo "# One git-refs pin per top-level flake input; Renovate bumps each branch HEAD and the"
  echo "# flake-inputs packageRule re-locks flake.lock via 'nix flake update <input>'. See renovate.json."
  echo ""
} > "$out"

for name in $(jq -r '.locks.nodes.root.inputs | keys[]' <<<"$meta"); do
  for s in "${SKIP[@]}"; do [[ "$name" == "$s" ]] && continue 2; done

  node=$(jq -r --arg n "$name" '.locks.nodes.root.inputs[$n]' <<<"$meta")
  type=$(jq -r --arg k "$node" '.locks.nodes[$k].original.type' <<<"$meta")
  rev=$(jq -r --arg k "$node" '.locks.nodes[$k].locked.rev' <<<"$meta")

  if [[ "$type" != "github" ]]; then
    echo "WARN: skipping non-github input '$name' (type=$type) — extend this script to support it" >&2
    continue
  fi

  owner=$(jq -r --arg k "$node" '.locks.nodes[$k].original.owner' <<<"$meta")
  repo=$(jq -r --arg k "$node" '.locks.nodes[$k].original.repo' <<<"$meta")
  url="https://github.com/$owner/$repo"

  # Branch the input follows: the explicit `ref` if pinned, else the repo's default branch
  # (the same branch a bare `github:owner/repo` URL resolves to).
  ref=$(jq -r --arg k "$node" '.locks.nodes[$k].original.ref // empty' <<<"$meta")
  if [[ -z "$ref" ]]; then
    ref=$(git ls-remote --symref "$url" HEAD | awk '/^ref:/{sub("refs/heads/","",$2); print $2; exit}')
  fi

  {
    echo "# renovate: datasource=git-refs depName=$name packageName=$url branch=$ref"
    echo "$name = \"$rev\""
    echo ""
  } >> "$out"
done

echo "Wrote $out:" >&2
cat "$out" >&2
