preload = ~/Pictures/backgrounds/Hydrogen_Remixed.png

wallpaper = DP-2,~/Pictures/backgrounds/Hydrogen_Remixed.png
wallpaper = DP-3,~/Pictures/backgrounds/Hydrogen_Remixed.png

splash = false
ipc = off