# Completions for the `claude` wrapper function (fishconfig.d/fish_functions.fish).
# Only the wrapper's OWN flag is declared here — everything else is Claude Code's own
# completion surface, which this must not shadow.
#
# The candidate list is generated by __claude_cpa_profiles from the *_CPA_TOKEN vars that
# secrets.fish exports, so a newly added gateway completes with no edit to this file.
complete -c claude -l cpa -x -a "(__claude_cpa_profiles)" \
    -d "Route through a CLIProxyAPI gateway instead of the OAuth login"
