apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bjw-s
  pass_credentials_all: false
  password: ""
  url: https://bjw-s-labs.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ananace
  pass_credentials_all: false
  password: ""
  url: https://ananace.gitlab.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: triliumnext
  pass_credentials_all: false
  password: ""
  url: https://triliumnext.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: rook-release
  pass_credentials_all: false
  password: ""
  url: https://charts.rook.io/release
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: democratic-csi
  pass_credentials_all: false
  password: ""
  url: https://democratic-csi.github.io/charts/
  username: ""
